
language: node_js

node_js:
  - '14'

before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
    - master


deploy:
  provider: heroku
  app: rikabal-ng-final
  skip_cleanup: true
  api_key: 817adf85-5ec3-4aaa-93cf-50da4ba993e9
