
language: node_js

node_js:
  - '14'
addons:
  chrome: stable
before_install:
  - npm install -g @angular/cli
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:9876/
install: npm install

branches:
  only:
    - master


deploy:
  provider: heroku
  app: rikabal-ng-final
  api_key:
    secure: "817adf85-5ec3-4aaa-93cf-50da4ba993e9"
